title: rukeba.com
description: Блог, песенник и ссылки, которые ведёт rukeba.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rukeba.com"
permalink: /:categories/:slug/
locale: ru-RU
lang: ru-RU
date_format: "%-d %b %Y, %H:%M"
future: false

google_analytics: UA-1638627-8

twitter:
  username: rukeba

logo: http://rukeba.com/assets/img/r.png
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-sitemap

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable: true

highlighter: none

empty_tags: []

feed:
  path: /feed/index.xml


collections:
  blog_tags:
    output: true
    permalink: /by-the-way/:name/
  songbook_tags:
    output: true
    #permalink: /songbook/:title/

defaults:
  - scope:
      path: ""
      type: "blog_tags"
    values:
      layout: blog-tag
  - scope:
      path: ""
      type: "songbook_tags"
    values:
      layout: songbook-tag


